"""empty message

Revision ID: 225fb0519d69
Revises: a31e96a6042d
Create Date: 2023-04-15 15:21:21.443846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225fb0519d69'
down_revision = 'a31e96a6042d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
