"""empty message

<<<<<<<< HEAD:migrations/versions/f416352fd573_.py
Revision ID: f416352fd573
Revises: 6caa2d409c8c
Create Date: 2023-03-25 10:33:13.813099
========
Revision ID: 34cc988b85e4
Revises: 642d435c3dda
Create Date: 2023-03-20 13:15:20.177975
>>>>>>>> origin/develop:migrations/versions/34cc988b85e4_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/f416352fd573_.py
revision = 'f416352fd573'
down_revision = '6caa2d409c8c'
========
revision = '34cc988b85e4'
down_revision = '642d435c3dda'
>>>>>>>> origin/develop:migrations/versions/34cc988b85e4_.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
